dataset:
  name: "stingning/ultrachat"
  subname: "all"

model:
  # 0.125B
  # n_dim: 768
  # n_layer: 12
  # n_head: 12
  # dim_head: 64
  # ff_ratio: 4.0
  # ff_dropout: 0.0 # 0.0 for pretraining
  # ex_ratio: 1.2
  # 0.7B
  # n_dim: 1536
  # n_layer: 24
  # n_head: 16
  # dim_head: 96
  # ff_ratio: 4.0
  # ff_dropout: 0.0 # 0.0 for pretraining
  # ex_ratio: 1.2
  # 2.7B
  # n_dim: 2560
  # n_layer: 32
  # n_head: 32
  # dim_head: 80
  # ff_ratio: 4.0
  # ff_dropout: 0.0 # 0.0 for pretraining
  # ex_ratio: 1.2
  # 1.3B
  n_dim: 2048
  n_layer: 24
  n_head: 24
  dim_head: 128
  ff_ratio: 4.0
  ff_dropout: 0.1 # 0.1 for SFT
  ex_ratio: 1.2

pretraining:
  # 0.125B
  # pretrain_length: 1024
  # batch_size_per_gpu: 32
  # batch_size: 500000
  # learning_rate: 2.0e-3
  # weight_decay: 0.1
  # 0.7B
  # pretrain_length: 1024
  # batch_size_per_gpu: 24
  # batch_size: 500000
  # learning_rate: 2.5e-4
  # weight_decay: 0.1
  # 2.7B
  # pretrain_length: 1024
  # batch_size_per_gpu: 6
  # batch_size: 1000000
  # learning_rate: 1.6e-4
  # weight_decay: 0.1
  # 1.3B
  pretrain_length: 2048
  batch_size_per_gpu: 4
  batch_size: 256 # not represent token in SFT
  learning_rate: 5.0e-5
  weight_decay: 0.1

  # lr_scheduler
  warmup_iters: 375
  lr_decay_iters: 26000
  min_learning_rate: 2.0e-5

path:
  save: /home/zzhang18/proj/CS554_NLP_Team7/saved_models/
  load: /home/zzhang18/proj/CS554_NLP_Team7/saved_models/latest.pt
